# 1.4.4 Smoothing Images

## Kernel Convolution

In [4]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
import os

In [5]:
resource_path = os.getcwd() + '/resource/'

In [6]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [7]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [8]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [9]:
img

array([[7, 6, 0, 9, 7, 3, 8, 9, 7, 1, 0, 6],
       [1, 8, 2, 8, 3, 4, 8, 3, 4, 3, 1, 1],
       [7, 2, 7, 5, 6, 2, 8, 9, 5, 2, 2, 2],
       [4, 5, 3, 8, 2, 6, 6, 3, 9, 1, 1, 7],
       [2, 8, 5, 1, 9, 4, 3, 6, 2, 5, 4, 3],
       [5, 6, 9, 9, 1, 5, 5, 5, 5, 1, 3, 3],
       [7, 0, 6, 5, 6, 5, 7, 5, 2, 4, 9, 1],
       [5, 4, 0, 5, 2, 4, 8, 0, 9, 3, 4, 8],
       [6, 8, 8, 4, 8, 0, 2, 6, 3, 3, 9, 1],
       [0, 4, 0, 8, 9, 3, 3, 5, 2, 7, 7, 4],
       [6, 8, 9, 3, 1, 5, 2, 9, 1, 9, 5, 5],
       [5, 0, 4, 1, 8, 6, 7, 3, 7, 1, 2, 2]])

In [10]:
h,w=img.shape

In [11]:
print(h,w)

12 12


In [12]:
#[*range(-2,3)]

In [13]:
dst = np.zeros((h,w),np.int)

In [14]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [15]:
img

array([[7, 6, 0, 9, 7, 3, 8, 9, 7, 1, 0, 6],
       [1, 8, 2, 8, 3, 4, 8, 3, 4, 3, 1, 1],
       [7, 2, 7, 5, 6, 2, 8, 9, 5, 2, 2, 2],
       [4, 5, 3, 8, 2, 6, 6, 3, 9, 1, 1, 7],
       [2, 8, 5, 1, 9, 4, 3, 6, 2, 5, 4, 3],
       [5, 6, 9, 9, 1, 5, 5, 5, 5, 1, 3, 3],
       [7, 0, 6, 5, 6, 5, 7, 5, 2, 4, 9, 1],
       [5, 4, 0, 5, 2, 4, 8, 0, 9, 3, 4, 8],
       [6, 8, 8, 4, 8, 0, 2, 6, 3, 3, 9, 1],
       [0, 4, 0, 8, 9, 3, 3, 5, 2, 7, 7, 4],
       [6, 8, 9, 3, 1, 5, 2, 9, 1, 9, 5, 5],
       [5, 0, 4, 1, 8, 6, 7, 3, 7, 1, 2, 2]])

In [16]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  21, -15,  13, -13,   0,   9, -18,  -2,   4,  -2,   0],
       [  0, -19,  16,  -9,  12, -16,   7,  17,  -4,  -3,   2,   0],
       [  0,   3, -13,  21, -21,  10,   4, -18,  25, -13, -10,   0],
       [  0,  14,  -1, -27,  28,  -7,  -9,  11, -17,  12,   4,   0],
       [  0,   2,  10,  20, -25,   5,   0,  -1,  10, -13,  -5,   0],
       [  0, -23,  10,  -6,  11,  -2,   5,   6, -15,   1,  24,   0],
       [  0,   3, -23,   9, -15,   1,  19, -28,  28,  -8, -13,   0],
       [  0,  10,  20, -13,  17, -17,  -9,  14,  -8, -10,  21,   0],
       [  0,   0, -29,  16,  16,  -5,   0,   0,  -8,   7,   3,   0],
       [  0,  13,  21,  -7, -21,   8, -16,  25, -23,  22,  -3,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [17]:
img = cv2.imread(resource_path + 'lena.png', 0)

In [18]:
h,w=img.shape

In [19]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [20]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [21]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()