# 1.5.2 Harris Corner Detection

## Harris Corner Detector in OpenCV

In [1]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt

In [2]:
resource_path = os.getcwd() + '/resource/'

In [3]:
filename = resource_path + 'horse.bmp'
img = cv2.imread(filename)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
gray = np.float32(gray)
dst = cv2.cornerHarris(gray,2,3,0.04)

In [4]:
#result is dilated for marking the corners, not important
dst = cv2.dilate(dst,None)

In [5]:
# Threshold for an optimal value, it may vary depending on the image.
img[dst>0.001*dst.max()]=[0,0,255]

In [6]:
cv2.imshow('dst',img)
if cv2.waitKey(0) & 0xff == 27:
    cv2.destroyAllWindows()

## with Trackbar

In [7]:
def nothing(x):
    pass

In [8]:
cv2.namedWindow('image')
cv2.createTrackbar('threshold', 'image', 10, 1000, nothing)
while(1):
    k = cv2.waitKey(1) & 0xFF
    if k == 27:
        break
    threshold = cv2.getTrackbarPos('threshold', 'image')
    if(threshold <= 1):
        threshold = 1
    img = cv2.imread(filename)
    img[dst > 1. / threshold * dst.max()] = [0, 0, 255]
    cv2.imshow('image',img)
cv2.destroyAllWindows()

## Corner with SubPixel Accuracy

In [9]:
filename = resource_path + 'horse.bmp'
img = cv2.imread(filename)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [10]:
# find Harris corners
gray = np.float32(gray)
dst = cv2.cornerHarris(gray,2,3,0.04)
dst = cv2.dilate(dst,None)
ret, dst = cv2.threshold(dst,0.01*dst.max(),255,0)
dst = np.uint8(dst)
print(ret, dst.shape)

680406.48 (446, 350)


In [11]:
# find centroids
ret, labels, stats, centroids = cv2.connectedComponentsWithStats(dst)

In [12]:
# define the criteria to stop and refine the corners
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.001)
corners = cv2.cornerSubPix(gray,np.float32(centroids),(5,5),(-1,-1),criteria)

In [13]:
# Now draw them
res = np.hstack((centroids,corners))
res = np.int0(res)
print(res)

[[175 217 175 217]
 [338   2 337   3]
 [209   7 207   7]
 ...
 [174 444 174 444]
 [200 444 198 443]
 [285 444 285 441]]


In [14]:
img[res[:,1],res[:,0]]=[0,0,255]
img[res[:,3],res[:,2]] = [0,255,0]
cv2.imwrite('subpixel5.png',img)

True

In [16]:
cv2.imshow('dst', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
res[:,-1]

array([217,   3,   7,  10,  17,  17,  23,  27,  42,  43,  43,  48,  58,
        59,  68,  67,  69,  72,  85,  89,  97,  97, 107, 109, 110, 120,
       122, 125, 128, 139, 136, 145, 145, 146, 143, 145, 147, 149, 152,
       153, 153, 155, 154, 157, 158, 157, 160, 162, 161, 163, 164, 165,
       166, 166, 167, 169, 167, 186, 171, 175, 176, 177, 178, 188, 174,
       178, 179, 182, 182, 185, 188, 188, 189, 189, 195, 194, 195, 199,
       201, 202, 209, 206, 205, 207, 210, 209, 213, 211, 212, 220, 217,
       218, 214, 220, 221, 215, 220, 220, 224, 225, 220, 226, 226, 227,
       231, 231, 228, 235, 238, 237, 242, 241, 242, 241, 241, 241, 242,
       244, 245, 251, 254, 256, 257, 259, 261, 262, 263, 263, 264, 265,
       264, 266, 265, 263, 269, 274, 269, 270, 273, 274, 273, 275, 278,
       281, 277, 278, 276, 279, 280, 282, 279, 284, 286, 294, 294, 294,
       285, 291, 290, 292, 291, 291, 296, 293, 293, 295, 297, 294, 290,
       300, 296, 299, 294, 299, 303, 304, 313, 310, 303, 307, 30

In [19]:
for i in range(res.shape[0]):
    cv2.circle(img,(res[i,0],res[i,1]),2,(0,0,255),-1)
    cv2.circle(img,(res[i,2],res[i,3]),3,(0,255,0),-1)

In [21]:
cv2.imshow('dst', img)
cv2.waitKey(0)
cv2.destroyAllWindows()