In [90]:
import cv2
import numpy as np
import os

In [91]:
resource_path = os.getcwd() + '/resource/'
img = cv2.imread(resource_path + 'messi5.png',0)
img2 = cv2.imread(resource_path + 'messi5.png',0)
cv2.imshow('image',img)
k = cv2.waitKey(0)
cv2.destroyAllWindows()

In [92]:
print(img)

[[ 32  34  35 ...  55  54  52]
 [ 33  34  34 ...  52  53  52]
 [ 33  34  33 ...  51  53  54]
 ...
 [113 112 114 ...  91  92  95]
 [111 102 112 ...  96 109 109]
 [113 104 106 ...  90 101 104]]


In [93]:
kernel = np.zeros((3,3),dtype=np.uint8)

In [94]:
## 중심으로 모든 값을 곱해서 더한게 합성곱이다.

In [95]:
print(img)
print(img2)

[[ 32  34  35 ...  55  54  52]
 [ 33  34  34 ...  52  53  52]
 [ 33  34  33 ...  51  53  54]
 ...
 [113 112 114 ...  91  92  95]
 [111 102 112 ...  96 109 109]
 [113 104 106 ...  90 101 104]]
[[ 32  34  35 ...  55  54  52]
 [ 33  34  34 ...  52  53  52]
 [ 33  34  33 ...  51  53  54]
 ...
 [113 112 114 ...  91  92  95]
 [111 102 112 ...  96 109 109]
 [113 104 106 ...  90 101 104]]


In [96]:
w,h = img.shape
kw,kh = kernel.shape

In [97]:
print( kw * kh)

9


In [98]:
kernel = np.zeros((3,3), dtype=np.int8)
for i in range(kw):
    for j in range(kh):
        kernel[i,j] = 1
        
kernel[1,1] = 6

In [99]:
print(kernel)

[[1 1 1]
 [1 6 1]
 [1 1 1]]


In [100]:
for i in range(w-1):
    for j in range(h-1):
        if not(i == 0 or j == 0 or i == w or j == h):
            sum = 0
            for z in range(kw):
                for k in range(kh):
                    sum += img[i-1+z, j-1+k] * kernel[z,k]
            temp = int(sum / (kw * kh))
            if temp >= 255:
                img2[i,j] = 255
            else:
                img2[i,j] = temp

In [101]:
print(img)
print(img2)

[[ 32  34  35 ...  55  54  52]
 [ 33  34  34 ...  52  53  52]
 [ 33  34  33 ...  51  53  54]
 ...
 [113 112 114 ...  91  92  95]
 [111 102 112 ...  96 109 109]
 [113 104 106 ...  90 101 104]]
[[ 32  34  35 ...  55  54  52]
 [ 33  52  52 ...  82  82  52]
 [ 33  52  51 ...  81  82  54]
 ...
 [113 173 174 ... 149 149  95]
 [111 166 171 ... 150 159 109]
 [113 104 106 ...  90 101 104]]


In [102]:
cv2.imshow('image',img)
cv2.imshow('image2',img2)
k = cv2.waitKey(0)
cv2.destroyAllWindows()

In [103]:
for i in range(2):
    for j in range(2):
        if not(i == 0 or j == 0 or i == w or j == h):
            print(int(img[i-1,j-1] * kernel[0,0] + img[i-1,j] * kernel[0,1] + img[i-1,j+1] * kernel[0,2] +
            img[i,j-1] * kernel[1,0] + img[i,j] * kernel[1,1] + img[i,j+1] * kernel[1,2] +
            img[i+1,j-1] * kernel[2,0] + img[i+1,j] * kernel[2,1] + img[i+1,j+1] * kernel[2,2]))
            print(i,j)


472
1 1


In [104]:
print(img[2,2] * kernel[2,2])

33
